### ISSUE TITLE
Create Markdown Docs

### ISSUE THREAD

**Issue by sadainiqrar** [pyBae-py/os-lab-project-01#1]
- Readme file in Git comes with **.md** extensions that stands for **markdown**
- HTML is markup
- Except for very special cases where markdown doesn't provide the components, don't use markups in markdown files

**Comment by sajeell** [comment]
Okay Sir, I will take care next time IN SHA ALLAH! ❇️

**Comment by sajeell** [comment]
I have now used Markdown language, in the Details.md file :-)
